### ISSUE TITLE
Update TiddlyDesktop

### ISSUE THREAD

**Issue by kookma** [Jermolene/TiddlyDesktop#101]
Is there any plan to update the TiddlyDesktop?
Right Click does not work? If you close the unsaved TW files, next time you open TiddlyDesktop you have to clean the configuration folder, if not it will stop working and will not open the TW files! It also seems the Chromium used here is an old version!

**Comment by tfeb** [comment]
I'd like to add my support to this.  For people like me, who have used single-file TWs for a very long time, TiddlyDesktop looks like the only reasonable hope for a future which isn't just full of pain and death after Firefox commits suicide in November.  There *needs* to be some tool which will support TW in a painless way (which node.js is not as it stands) for those of us with more than 10 years worth of daily notes in TWs.

**Comment by jockster74** [comment]
I am using TiddlyDesktop version 0.0.8 on a daily basis to update [mGSD](http://mgsd.tiddlyspot.com/#mGSD) files. I used Firefox for a long time, but eventually I just had too many issues and switched to TiddlyDesktop instead. The downside to that is now I have yet another application always running. The upside is I am no longer chained to Firefox and at least for me TiddlyDesktop has worked very well. It does crash at times, but not every week, and it is in heavy use from Monday - Friday. 

I sure hope there will be new versions of TiddlyDesktop released in the future.

**Comment by Jermolene** [comment]
Hi @kookma @tfeb @jockster74 thanks for the feedback, and sorry for the delayed response. There is now an updated release of TiddlyDesktop, please give it a try:

https://github.com/Jermolene/TiddlyDesktop/releases/tag/v0.0.9

**Comment by kookma** [comment]
Many thanks Jeremy.
I will send my feedback.

Best



Mohammad Rahmani, Ph.D.
Assistant Professor of Chemical Engineering

President, Mahshahr Campus
Amirkabir University of Technology
m.rahmani@aut.ac.ir
aut.ac.ir/m.rahmani

PO Box 15875-4413 | Tehran, Iran
424 Hafez Ave, Amirkabir Uni of Tech | Chemical Eng Dep

(o) +98.21.6454.3198 | (f) +98.21.6640.5847 | GMT +3.5
