### ISSUE TITLE
Option for sorting in list-links macro

### ISSUE THREAD

**Issue by TheBashar** [Jermolene/TiddlyDesktop#103]
In Chrome the list-links macro returns the tiddlers in creation time order.  I find that very helpful so that I can control the order without having to prepend the tiddler names with an ordinal.  In TiddlyDesktop however the macro returns the tiddlers in alphabetical order.  While I'm sure some use-cases are better suited to that ordering, it would be very nice if there was an option to select the default sort order.  Thanks!

**Comment by pmario** [comment]
just add a sort parameter
instead of: `<<list-links filter:"[tag[Core Macros]]">>`
use: `<<list-links filter:"[tag[Core Macros]sort[creaded]]">>`
or:  `<<list-links filter:"[tag[Core Macros]!sort[creaded]]">>` for inverted order

**Comment by TheBashar** [comment]
Oh, thank you! I did not know that was possible.
