### ISSUE TITLE
Minor: App tray icon has useless (?) "this is my tooltip"

### ISSUE THREAD

**Issue by jdittrich** [Jermolene/TiddlyDesktop#108]
Platform: Ubuntu 16.04 unity

Problem: The tray icon of Tiddly desktop has a menu with the first entry being "this is my tooltip". The entry seems to be useless.

Solution: Get rid of the entry

**Comment by Jermolene** [comment]
Thanks @jdittrich that was an oversight; will be fixed in v0.0.10
