### ISSUE TITLE
Crash when closing TiddlyDesktop on OSX 10.12.6 (Sierra)

### ISSUE THREAD

**Issue by nderambure** [Jermolene/TiddlyDesktop#112]
Is there a log file for crash infos somewhere so I could see what happen ?
Each time I close TiddlyDesktop, I have the popup saying the app has crashed.

Anyway, thx for your work !

**Comment by nderambure** [comment]
It says nwjs failed to stop... any idea ?

**Comment by Jermolene** [comment]
HI @nderambure apologies for the delay. I think the logs from nw.js should be in the system "Console” app. I have seen this problem too. Does it occur for you every time the app exits?

**Comment by nderambure** [comment]
Hi @Jermolene !
No problem. I should have looked in console app before sorry...
But there is nothing there, no error message.... Can't find any info about the crash.
And yes, it appears each time I close the app.
I'll keep on digging... thx anyway for your time !

**Comment by Jermolene** [comment]
I'm still getting this error, and have found [others with the same symptom](https://github.com/nwjs/nw.js/issues/5924) but no solution yet.
