### ISSUE TITLE
Impossible to export tiddlers

### ISSUE THREAD

**Issue by somenxavier** [Jermolene/TiddlyDesktop#118]
![captura de pantalla_2017-12-05_20-02-03](https://user-images.githubusercontent.com/89915/33625233-3bb07048-d9f7-11e7-964d-4657907ad9ef.png)
Please fix this

**Comment by Jermolene** [comment]
I believe that this problem should be fixed with the new v0.0.10:

https://github.com/Jermolene/TiddlyDesktop/releases/tag/v0.0.10

Please let me know how you get on.

**Comment by somenxavier** [comment]
Yes. Fixed in 0.0.10

**Comment by Jermolene** [comment]
Great, thanks @somenxavier

**Comment by Wheels00** [comment]
I get the same problem with v0.0.11 on Mac. Can we reopen this issue. 
<img width="565" alt="screen shot 2018-01-14 at 3 43 14 pm" src="https://user-images.githubusercontent.com/12003601/34912929-68406b94-f942-11e7-8385-3be73cf06382.png">

**Comment by somenxavier** [comment]
I have also the same issue with 0.0.11

**Comment by gmolyneux** [comment]
Same Behavior on 0.0.12 in OpenSUSE Leap 42.2 running KDE:

![tiddlywikiexportfailure](https://user-images.githubusercontent.com/36090425/35759649-cfb80d62-082f-11e8-9177-eeae06a22be3.png)

Note, I can't export in any format (CSV, HTML, TXT, or JSON).

Thanks for your efforts.

**Comment by Jermolene** [comment]
This should be fixed in the latest v0.0.13:

https://github.com/Jermolene/TiddlyDesktop/releases/tag/v0.0.13
