### ISSUE TITLE
Remember size of TiddlyDesktop window(s)

### ISSUE THREAD

**Issue by huggyfee** [Jermolene/TiddlyDesktop#12]
The application seems to remember which windows were open, but not the location / size of the windows when the application / window was closed - including the main tiddlywiki list window. This would be an excellent feature, especially if (on the mac at least) it also knew the desktop number that it was last opened on as well (particularly for multi-monitor people). I often do different tasks on different desktops, and have a tiddlywiki open relating to that task.
Excellent so far, by the way - it's very useable already in a very short space of time - thanks.

**Comment by Jermolene** [comment]
This was actually fixed in v0.0.4
