### ISSUE TITLE
Close/Exit application on ctrl+w or ctl+q

### ISSUE THREAD

**Issue by ch3paz** [Jermolene/TiddlyDesktop#122]
Add an "close application" keybinding for users of tiling windowmanagers (e.g. i3).

**Comment by Jermolene** [comment]
Thanks @ch3paz, and apologies for the delayed response.

I'm not familiar with Linux. On OS X, we get support for cmd-Q to quit the app by virtue of the standard menu bar. Does that not happen with Linux?

**Comment by ch3paz** [comment]
Hello Jermolene,

so i'm not aware of 'cmd+Q' :)
But it seems not to be the same as 'ctrl+q'. I played arround a bit and found no key-combination that closes tiddlydesktop clean. What works is to go over the trayicon --> quit.

**Comment by hxmuller** [comment]
@ch3paz,

Super-Shift-Q closes/kills a window if you are using i3wm. Where 'Super' is the 'Windows' key.

**Comment by ch3paz** [comment]
@hxmuller Thanks, but also after another 2 years of using i3 i don't want to KILL a program, i want to exit it in a clean way.

**Comment by hxmuller** [comment]
@ch3paz I have been using i3wm a year now, I like it a lot.

from the i3wm manpage:

> **Mod1+Shift+q**
> Kills the current window. This is equivalent to "clicking on the close button", meaning a polite request to the application to close this window. For example, Firefox will save its session upon such a request. If the application does not support that, the window will be killed and it depends on the application what happens.

As far as TiddlyDesktop goes, it simply closes the browser window that has focus. TiddlyDesktop does not have any state to speak of that requires saving, it is enough that the TiddlyWiki site files are saved. And if you attempt to close a TiddlyWiki site file while changes have not been saved, you get a WARNING that there are unsaved changes.

So Super-Shift-Q is the way to go. I close all my applications using this method and have not suffered issues.

**Comment by ch3paz** [comment]
@hxmuller 
For shure 2 years ago exactly this killed my tiddlys, i hadn't written this issue when there wasn't a problem like that. Currently i don't use tiddly anymore as the formerly "browsersolution" was cool but the "desktopversion" was not. If it works nowadays, fine (but i don't care any more).

In my opinion it's also an bad design when an program doesn't respect some standard keybindings like ctrl+q, ctrl+w or something like these by itself, as you can't always know how an WM ends an window. 

Both programs (tiddly and i3) have shurely evolved (using i3 since ~2014 i think) and if this feature is needed or not: this issue could be solved or closed by @Jermolene - that's on his decission.

So Super-Shift-Q is NOT the way to go. Sorry, but you've given an hint/suggestion, but not the solution on the issue here.

**Comment by ch3paz** [comment]
Don't know if this was fixed or not, as i'm not using tiddly any more i'll close this issue.
