### ISSUE TITLE
Where is "Export tiddler " saved?

### ISSUE THREAD

**Issue by braykov** [Jermolene/TiddlyDesktop#123]
When I select Export tiddler -> HTML I get the popup "Saved Wiki", but I cannot find the save location.
It is not in the Wiki folder, nor it is in the default Downloads folder.
TD should ask for a save location as it does in the browser.

**Comment by pmario** [comment]
in the browser download directory.

**Comment by pmario** [comment]
uups, didn't see that it's TiddlyDesktop not TW ... just ignore my last comment.

**Comment by Jermolene** [comment]
Hi @braykov did this work in v0.0.8? I'm wondering if the latest nw.js somehow breaks TiddlyDesktop's ability to download files...

**Comment by manheraz** [comment]
Hi @Jermolene!

Not working for me in Windows 10 Pro 1709, using TiddlyDesktop 0.0.9.

A Windows dialog pops up saying "You'll need a new app to open this blob" and just shows the Store. This happens with all the export file formats (CSV, JSON, single HTML...)

![tiddlydesktop export](https://user-images.githubusercontent.com/4477124/34554688-7122888a-f12e-11e7-93f2-c5ac7a74f27a.png)

Thank you for TiddlyWiki!

**Comment by Jermolene** [comment]
Hi @braykov I believe that this problem is resolved by the fix for #127. I'll release v0.0.10 imminently, please give it a try when you get a chance

**Comment by braykov** [comment]
Yes, v0.0.10 has this fixed. The Save As dialog opens now.
Thank you!
