### ISSUE TITLE
External audio file do not work

### ISSUE THREAD

**Issue by juanerasmoe** [Jermolene/TiddlyDesktop#125]
(relative) Links to external audio file do not open within tiddlyDesktop or external software in Ubuntu.

**Comment by Jermolene** [comment]
Hi @juanerasmoe I think this issue is fixed by 5444a7f54b042f12b9714ac2d914920196616430; please look out for the imminent release of v0.0.10 and give it a try

**Comment by juanerasmoe** [comment]
This is indeed solve in 0.0.10

**Comment by Jermolene** [comment]
Great, thanks @juanerasmoe
