### ISSUE TITLE
Not saving files on Mac OS X High Sierra

### ISSUE THREAD

**Issue by babaks77** [Jermolene/TiddlyDesktop#128]
After updating to Mac OS X High Sierra, TiddlyWiki Desktop 0.8 stopped saving files, with the error message: "It's not possible to save changes. This could be because your browser doesn't support saving (instead, use FireFox if you can), or because the pathname to your TiddlyWiki file contains illegal characters".

I installed TiddlyWiki Desktop 0.9, but it also does not save files on Mac OS X High Sierra with the same error message. Additionally, when opening a tiddlywiki file and intermittently (when creating a new tiddler, etc.) this version also generates the message: "There is no application set to open the URL javascript:;. Search the App Store for an application that can open this document, or choose an existing application on your computer."

**Comment by Jermolene** [comment]
Thanks @babaks77 - am I right in thinking you are using TiddlyWiki Classic?

**Comment by babaks77** [comment]
Yes, I'm using tiddlywiki classic.
