### ISSUE TITLE
Mac App Name shows as 'nwjs'

### ISSUE THREAD

**Issue by comdotdom** [Jermolene/TiddlyDesktop#129]
Version 0.0.10

No biggie, but would have expected "TiddlyDesktop"
![screenshot 2018-01-08 12 41 08](https://user-images.githubusercontent.com/5439759/34671143-40477ae0-f471-11e7-85cf-d5caf3f2bf04.png)

**Comment by Jermolene** [comment]
Hi @comdotdom the hold-up here is that I need to improve the build process to be able to perform this step:

> The first item of application menu shows nwjs instead of your-app-name. To fix it, you need to set the value of CFBundleName in all files of nwjs.app/Contents/Resources/*.lproj/InfoPlist.strings to  your-app-name instead of nwjs.

From http://docs.nwjs.io/en/latest/For%20Users/Advanced/Customize%20Menubar/#mac-os-x

We just need a tiny JS app...
