### ISSUE TITLE
Mac Icon - Are the layers right ?

### ISSUE THREAD

**Issue by comdotdom** [Jermolene/TiddlyDesktop#130]
The Mac App icon looks like the black cat is behind the yellow circle rather than on top of it ?

![screenshot 2018-01-08 12 43 57](https://user-images.githubusercontent.com/5439759/34671226-9d24a440-f471-11e7-9b57-dc07de4ed02e.png)

**Comment by Jermolene** [comment]
Hi @comdotdom that's weird. I'm seeing the icon normally on macOS Sierra 10.12.6:

![tiddlydesktop icon](https://user-images.githubusercontent.com/174761/34671306-fb502d1e-f471-11e7-964b-3d3086bb48a8.png)

The Dock does do some caching, so it may be worth killing it if you know how, or logging in and out again.

**Comment by comdotdom** [comment]
I'm on latest High Sierra - maybe that's something to do with it.
Logged in/out - same look.

**Comment by Jermolene** [comment]
I use an app called IconSlate to generate the `.icns` file (see the icons folder in this repo). It may be worth downloading the repo and seeing if the file displays correctly on your machine?

**Comment by comdotdom** [comment]
Will do. Just setting off on 4 hr journey. 
(Brief pause for geography)

**Comment by comdotdom** [comment]
Downloaded the icon file, opened it and then when I looked at my dock the icon looked how it's supposed to ! Suggests to me that your diagnosis of dock caching was correct.
Have now upgraded to 0.0.11 and all remains well with the icon.
