### ISSUE TITLE
tm-open-window throws error in new FramedEngine / framed.js

### ISSUE THREAD

**Issue by BurningTreeC** [Jermolene/TiddlyDesktop#139]
Hi, I'm not sure if this is a bug of if I'm overdoing it - this behaviour only appears in TiddlyDesktop:

If I open an external window from within TiddlyDesktop where I can create new Tiddlers and edit them because there's a story-river to do so...
everything works fine unless I close the window and open it again and create a new tiddler. Then console tells me that in framed.js at new FramedEngine it cannot read 'document' of null. After that also factory.js throws an error that it cannot read 'fixedHeight' of null.

It seems to me that windows.js (tm-open-window) and framed.js do not interact correctly

Simon

**Comment by Jermolene** [comment]
Hi @BurningTreeC sorry to be late to this.

> If I open an external window from within TiddlyDesktop where I can create new Tiddlers and edit them because there's a story-river to do so...

Do you still have the wikitext for that window? or were you opening an existing tw.com tiddler into a new window?

**Comment by BurningTreeC** [comment]
Hi @Jermolene - no problem it's not a big issue

It's the window that's created clicking the Rocket on http://rocketdock.tiddlyspot.com,
This is the new-window Tiddler: http://rocketdock.tiddlyspot.com/#%24%3A%2Fcore%2Fui%2FPageTemplate%2Frocketdock
