### ISSUE TITLE
Inline external images not displaying

### ISSUE THREAD

**Issue by patrickgardella** [Jermolene/TiddlyDesktop#140]
I'm pretty sure you know about this, but I'm opening an issue just in case.

I'm working on an 5.1.15 TiddlyWiki file, and I'm trying to put an image hosted on an external website inline. This works just fine (displays the image) in Chrome itself, but not in TiddlyDesktop 0.0.13 (or earlier versions). This is on Windows 7 Enterprise x64 Service Pack 1.

Desktop:
![desktop](https://user-images.githubusercontent.com/6595897/36914399-30078c32-1e1b-11e8-85a3-9dbff19c0f09.PNG)

Chrome:
![chrome](https://user-images.githubusercontent.com/6595897/36914409-36be93b8-1e1b-11e8-9f02-06daae99b64a.PNG)

The two Tiddlers are TiddlyWiki format on top and the Markup format on the bottom.

**Comment by Jermolene** [comment]
Hi @patrickgardella what format is the image? Can you show the full `[img[` tag you're using? Many thanks!

**Comment by patrickgardella** [comment]
It's a PNG, even though the URL doesn't say that:
`[img[https://www.medicaremadeclear.com/-/media/mmc%20redesign/mmc%20images/rte/finding_good_fit.ashx]]`

**Comment by Jermolene** [comment]
Hi @patrickgardella I wasn't able to duplicate the problem in a Windows 7 Virtual Machine on my Mac:

<img width="1346" alt="screenshot 2018-03-02 20 59 50" src="https://user-images.githubusercontent.com/174761/36921583-c62b5874-1e5c-11e8-817e-ee850033bab6.png">

I'm a bit stumped as to what could be going on. Perhaps it's worth re-installing TiddlyDesktop (including deleting the app data folder -- see the "Settings" dialogue for info).

**Comment by patrickgardella** [comment]
Hi, @Jermolene That was with a clean installation of TiddlyDesktop.  I originally had 0.0.9 installed, and when I had the problem, I deleted that, and installed 0.0.13.  I'll check again when I get back into the office on Monday.  The computer is very tightly locked down from a security perspective, so it may be this system, and not your app!

**Comment by patrickgardella** [comment]
It's not Monday like I said, but I did figure it out.  The computer I'm on is very tightly restricted, so it forces all new browser sessions to go through authentication. In Chrome, I'm already logged in.  In TiddlyDesktop (TD), I'm not.  So when the ZScaler firewall returns the 307 redirect when TD makes the call for the image, TD displays the broken image.  If I inspect the image, and then "Load in New Tab", and sign in, the image displays properly.

So I don't think there is anything you can do to fix that, unless you can add "Load Image in New Tab" to the right click menu in TD. 

Thanks for the help!

**Comment by Jermolene** [comment]
Hi @patrickgardella good to know, pesky security!

Might it be possible to include in your wiki an external iframe that gives you enough room to complete the authentication?

**Comment by patrickgardella** [comment]
It would, @Jermolene. But in this case, I'll just link to that page, since it's hosted by someone else. Thanks for the help!
