### ISSUE TITLE
External Attachments Plugin not working

### ISSUE THREAD

**Issue by ExoCode17** [Jermolene/TiddlyDesktop#142]
I am on Windows 10 and I tried with both the 32 and 64 bit versions. 

I load a new, empty TW file, I open it, I install the above mentioned plugin and I try to import an image (I tried importing various types of files from a variety of locations including at the same level as the TW file, under and above). I tried with both the import file button (the paperclip icon) and via drag and drop (dragging a file on the window shows the usual green bar before dropping). It doesn't matter the file type, its location or where I drop it in the windows, at this point the window goes black and shows a preview of the image (or the pdf or whatever) instead of the import dialog. Sometimes it shows instead the red popup 'internal javascript error...reload' but I have no way to reload the page (tried ctrl-r or f5). Sometimes this red box flashes for an instant and then the windows goes black as described above. At this point I need to close the window and restart NW.

Note that if the plugin is not installed everything works as it should and I can import anything with no error. But as I said, this is not my goal as these files get embedded decreasing the performance of my TW (which is not the goal of EAP neither).

Please help!

**Comment by ExoCode17** [comment]
![2018-03-21 17_47_40-developer tools - chrome-extension___bpdeplafbjkfabcdjdbibppeobkefplc_html_wiki-](https://user-images.githubusercontent.com/13753044/37723970-037de1ec-2d30-11e8-83fd-da5bae45bda8.png)
I just discovered that I could press F12 to enter dev view, here's a screen of the Internal Javascript Error that I managed to collect

**Comment by BurningTreeC** [comment]
Hi @ExoCode17 

have you tried checking both checkboxes for the absolute paths in the External Attachments Plugin -> Settings?

BTC

**Comment by ExoCode17** [comment]
Yes, nothing changed but I taken the above screenshot without them checked. Maybe it will give me a different error? I'll try it asap.

In the meantime I found this: https://groups.google.com/forum/#!topic/tiddlywiki/q2COyG-gKtM

It's a guy lamenting the same error!

**Comment by ExoCode17** [comment]
![2018-03-22 10_52_33-my tiddlywiki a non-linear personal web notebook](https://user-images.githubusercontent.com/13753044/37763382-2acfdffe-2dbf-11e8-9966-8d9409e4c81c.png)

Nothing changed! Just dropping an image in the TW are makes the screen black and I can't read console. Using the import button instead doesn't change the page therefore allowing me to take the screenshot and read the console.

**Comment by ExoCode17** [comment]
Anyone? @Jermolene ?

**Comment by Jermolene** [comment]
Thanks @ExoCode17 I'll take a look.

**Comment by ExoCode17** [comment]
Thanks @Jermolene , please let me know! 

TW is awesome and I was hoping of using its simplicity and flexibility tu run a pictures database. Unfortunately, external attachments in this case are a must and I am unable to get them to work. Changing the _canonical_uri of each image manually for me is not an option as I have more than 500 images in HD that I want to catalog (I am a digital artist). I am already using TW for a lot of things ranging from collecting poetry to managing role-playing campaigns and I would love to use it also for this purpose. I tried several galleries (chevereto, piwigo, lychee..) but nothing matches TW in doing what I want to achieve. 

Anything I can do to troubleshoot?

**Comment by Jermolene** [comment]
Thanks @ExoCode17 I've found the problem, and will explore a fix and report back.

**Comment by kalmir** [comment]
@Jermolene, I have encountered the same problem as @ExoCode17. Also Win 10, 32bit TiddlyDesktop.

**Comment by irlandos** [comment]
@Jermolene, I also have the same problem as @ExoCode17 and @kalmir. I am running Win7 64bit. The tiddlywiki is the 5.1.20 prerelease with the External attachment plugin installed. TiddlyDesktop is version 0.0.13 but I'm afraid I don't know whether it's 32-bit or 64-bit.

**Comment by Jermolene** [comment]
@Marxsal also raised this issue in the [discussion group](https://groups.google.com/d/topic/tiddlywiki/UwKuVkfJob0/discussion)

**Comment by Jermolene** [comment]
This should be fixed in the latest version of TW5: https://github.com/Jermolene/TiddlyWiki5/issues/4237
