### ISSUE TITLE
EPERM open with a TiddlyWiki 5

### ISSUE THREAD

**Issue by Tamh** [Jermolene/TiddlyDesktop#154]
Hello everyone, and thank you for your awesome job with TiddlyDesktop.

I have used TiddlyDesktop since version 0.0.8 with a particular TiddlyWiki.
However since past week, I have started having trouble with that file when trying to save the Wiki.
Using TiddlyDesktop 0.0.8 and/or TiddlyDesktop 0.0.13, I get the following messages, respectively:
![image](https://user-images.githubusercontent.com/2487582/42828570-4f17bc38-89ae-11e8-9dac-d799342f4059.png)
![image](https://user-images.githubusercontent.com/2487582/42828702-6feb712a-89ae-11e8-9383-06aeda7ec491.png)
The file name that is displayed in TiddlyDesktop 0.0.8 EPERM open error message remains the same, even after deleting the TD Settings folder.

I have checked permissions, moved the folder out of the OneDrive folder, and it doesn't work.
However, opening the TiddlyWiki in a browser, editing and saving works perfectly, no issues whatsoever.
Importing the browser edited TW file into TiddlyDesktop gives me the same message.

Do you have any idea what could be happening here? I can assure you, it was working before, and about Thu past week it stopped working.

**Comment by Jermolene** [comment]
Hi @Tamh I haven't seen that specific error before. Could you try it again, but before attempting to save the wiki, open the developer tools with the F12 key. You should see more detailed error information in the console tab.

What operating system are you using? Does the full path to the file contain spaces or accented characters?

**Comment by Tamh** [comment]
Hey Jermolene, thank you for following up.
Here it is a shot from the console.
![image](https://user-images.githubusercontent.com/2487582/42841576-21eef448-89d0-11e8-9296-e867b17238e7.png)
Last line repeats, and repeats, and repeats until:
![image](https://user-images.githubusercontent.com/2487582/42842804-d4fd6ddc-89d3-11e8-8a95-b21379bf30e9.png)

The lines referred as being in the actual TW file are referring to `$tw.utils.error` and `window.onerror` (which is a code block that has a comment `Use our custom error handler if we're in the browser`).

I'm using Windows 10 v1803 (b17134.165). The full path to the TW file is: `C:\Users\Tamashii\OneDrive\Documents\TiddlyWikis\Anime.html`, no spaces or special characters whatsoever.

**Comment by Jermolene** [comment]
Hi @Tamh it looks like the problem is that the Node.js process doesn't have permission to write to the backup file; presumably it's an issue with OneDrive or Windows, because the filepath looks OK.

**Comment by Tamh** [comment]
Yep, you're correct, I changed and moved the files out to a folder that has no permission issues and it worked now. Thanks for your help! Closing the issue.
