### ISSUE TITLE
Not support full screen mode by default

### ISSUE THREAD

**Issue by nash900** [Jermolene/TiddlyDesktop#155]
Seems it's not posible to open a tiddler with full screen mode by default. 

Env.:
* Version 0.0.13
* Windows 10

**Comment by Jermolene** [comment]
Hi @nash900 the logic to save and restore window positions is managed by nw.js so it's possible that this is fixed in later versions. I plan to do an update soon and will re-test then.

**Comment by nash900** [comment]
Thanks Jermolene, waiting for the new version.
