### ISSUE TITLE
Use TAB to input TAB in text box

### ISSUE THREAD

**Issue by nash900** [Jermolene/TiddlyDesktop#156]
Does it possible to use TAB key to input TAB itself in text box instead of jump to another box?

Env.:
* Version 0.0.13
* Windows 10

**Comment by Jermolene** [comment]
Hi @nash900 you can install the TW5 CodeMirror plugin; by default it inserts a tab character when you type the tab key.

**Comment by nash900** [comment]
@Jermolene, thanks a lot. The TW5 CodeMirror plugin works for TAB.
