### ISSUE TITLE
TiddlyDesktop Releases Tiddler on tiddlywiki.com is outdated

### ISSUE THREAD

**Issue by sahil48** [Jermolene/TiddlyDesktop#161]
https://tiddlywiki.com/#TiddlyDesktop

The current release is 0.0.13. Release history at https://tiddlywiki.com/#TiddlyDesktop only goes up to 0.0.8, and has a nice big green download button for the 0.0.8 release. This should continue to be updated.

**Comment by kookma** [comment]
Any chance for a new release? Is there any plan to resolve the issues on fullscreen and local menu (right click of mouse)?

**Comment by Jermolene** [comment]
Hi @sahil48 apologies, I think it was too ambitious to try to maintain the TiddlyDesktop release listing on tiddlywiki.com, so I've now replaced that tab with a link to the release listing on GitHub:

https://github.com/Jermolene/TiddlyWiki5/commit/b776f9fe90a08d407a6cd6fae8b304a9eac5190f

(@kookma I am preparing a new release now that will at least bring us up to the latest nw.js).
