### ISSUE TITLE
Default WIki and command line

### ISSUE THREAD

**Issue by AnthonyMuscio** [Jermolene/TiddlyDesktop#179]
TiddlyDesktop is great for managing ones local desktop with its access to run applications and open windows explorer. However it falls short of a full local application in so far as the wikis must be selected from the Main Window. This is great in many circumstances but once the user has an everyday wiki it is a little limiting. 

Would it be possible to flag a wiki in the list to open with TiddlyDesktop or a command line and thus shortcut used to launch a particular wiki?

Users could then autoload there key wiki in the startup process.

Thanks in advance

**Comment by Jermolene** [comment]
Hi @AnthonyMuscio this may be a dupe of #85

**Comment by AnthonyMuscio** [comment]
Transferd comment here to the above thread as its duplicate
