### ISSUE TITLE
"TiddlyDesktop" Tray entry doesn't work

### ISSUE THREAD

**Issue by BurningTreeC** [Jermolene/TiddlyDesktop#188]
I would expect the "TiddlyDesktop" Tray entry to raise the TD windows up in front, but it just doesn't do anything

OS: Linux (Manjaro/Arch)
TiddlyDesktop: latest prerelease

**Comment by jeancf** [comment]
I am on Manjaro/KDE and like to keep TiddlyDesktop in the system tray and not show it in the Task Manager. But the experience would be much more streamlined if by clicking on the icon I could:

* raise the window if it is minimized to the tray
* minimize the window if it is maximized

BTW, I love TiddlyDesktop: simple and effective. Thanks!

**Comment by Jermolene** [comment]
Hi @BurningTreeC @jeancf I'm afraid I usually only test on Windows and macOS, so it would be helpful to have some screenshots to understand what you're seeing. Are you talking about clicking on the tray icon itself, rather than its menu? There is a tray menu item labelled "TiddlyDesktop" with the version number, but that's disabled, is that the one you mean?

nwjs has some peculiarities in its attempts to smooth out the platform differences for this kind of thing.

**Comment by BurningTreeC** [comment]
![Bildschirmfoto von 2020-05-05 17-52-17](https://user-images.githubusercontent.com/9407182/81086917-66262c00-8ef9-11ea-9bf6-bdc065ec7417.png)

The first entry in the tray dropdown is selectable but without effect. That's what I meant

**Comment by Jermolene** [comment]
Thanks @BurningTreeC -- that's the first time I've seen the yellow tray icon, looks pretty cool. Here's what it looks like on macOS:

<img width="308" alt="image" src="https://user-images.githubusercontent.com/174761/81087263-66bac480-8ef1-11ea-9ada-e8b58aa2fec1.png">

It's not immediately obvious where the extra "TiddlyDesktop" menu item you're seeing on Linux comes from.

**Comment by jeancf** [comment]
Here is how it looks on mine (KDE Plasma):
![Screenshot_20200505_175453](https://user-images.githubusercontent.com/885845/81087465-0d0ac800-8efa-11ea-9bcf-7513101b9ac8.png)
What I meant is:

* raise the window by clicking on the icon if it is minimized to the tray
* minimize the window by clicking on the icon if it is maximized
* right click on the icon to access the popup menu

**Comment by Jermolene** [comment]
The strange this is that the code does not add the "TiddlyDesktop" icon, just the remaining 5 menu items, and the last two separators:

https://github.com/Jermolene/TiddlyDesktop/blob/master/source/js/main.js#L38-L75

I'm guessing that the Linux port of nwjs is automatically adding the menu item (possibly for platform consistency?), but I can't find any docs referencing this, and so can't add a menu handler for it.

**Comment by BurningTreeC** [comment]
Yes it's probably just a Linux thing  - for me it's not really important. I was just asking myself why it was there, clickable but without functionality
