### ISSUE TITLE
Clean install, launch screen is distorted

### ISSUE THREAD

**Issue by beerMT** [Jermolene/TiddlyDesktop#189]
I just downloaded the new release and when I launch it on a MBP 16" running macOS catalina v10.15.4, I get the following
<img width="985" alt="Screen Shot 2020-04-29 at 9 30 05 AM" src="https://user-images.githubusercontent.com/6117308/80614908-44f6a480-89fc-11ea-8003-6f217c3ad538.png">

**Comment by Jermolene** [comment]
Hi @beerMT that's quite some visual effect! I've not seen that before (I'm running the same version of Catalina). Can you still click buttons? If you click the "Help" window does the newly opened window have the same distortion? And do you get the same problem even after a restart?

**Comment by beerMT** [comment]
I can still click buttons and open a tiddlywiki, which does not display distorted. Main app page navigation is barely readable, but having used v0.0.13 the workflow is very similar if not the same. Problem persists through restarts. If you launch the Help or Add Wiki buttons the window appears as it should - undistorted.

**Comment by beerMT** [comment]
Spoke too soon, just launched one of the wikis and drilled down into a link and the screen distorts when it loads that page.
<img width="1702" alt="Screen Shot 2020-04-29 at 10 10 49 AM" src="https://user-images.githubusercontent.com/6117308/80619257-b6852180-8a01-11ea-98cc-b8586c8c3099.png">

**Comment by beerMT** [comment]
This was resolved after a computer restart. I think it's safe to assume it was an external influencer, since you are running the same OS and version.
