### ISSUE TITLE
wiki window showing html

### ISSUE THREAD

**Issue by jomonjohnn** [Jermolene/TiddlyDesktop#192]
With the latest( v0.0.14) linux 64 binary on arch linux, trying to open a newly created wiki will,

- display window with html source code instead of rendered view
- the wiki window wont be closed with close button 

![Screenshot_2020-05-09_10-41-30](https://user-images.githubusercontent.com/520044/81470652-ae886700-91e3-11ea-9d66-8c9f4354c14d.png)

Thinking of some missing dependency tried the installing TiddlyDesktop via [aur](https://aur.archlinux.org/packages/tiddlydesktop/) and the issue persists.

**Comment by Jermolene** [comment]
Hi @jomonjohnn sorry you've run into problems. I've seen that behaviour when the wiki file doesn't have an .HTML extension, could it be that?

**Comment by jomonjohnn** [comment]
@Jermolene 

>I've seen that behaviour when the wiki file doesn't have an .HTML extension, could it be that?

Yes, saving with .html extension solved the issue. Sorry for the stupid issue report and thank you for the support.

**Comment by Jermolene** [comment]
Hi @jomonjohnn no problem, glad it's sorted. I'll try to figure out a way to add a warning.

**Comment by basta** [comment]
This happened to me today on latest release, the file created from the app was missing the .html, I am on Fedora Linux
