### ISSUE TITLE
Blank window on first run (Win 7)

### ISSUE THREAD

**Issue by markpea** [Jermolene/TiddlyDesktop#20]
Just downloaded tiddydesktop-win-0.0.3 to my Windoze 7 desktop. Having extracted the files and run nw.exe I get a blank window titled 'node-webkit'. I would post a screenshot but there seems little point because it's just a blank bog standard windows window. Also F12 does nowt.
Cheers
Mark

**Comment by Jermolene** [comment]
Hi @markpea I'm closing this because it was raised against an earlier version. Please re-open if you still experience the problem with the latest v0.0.6 version.
