### ISSUE TITLE
The edit button under the toolbar cannot be displayed

### ISSUE THREAD

**Issue by gyuezhang** [Jermolene/TiddlyDesktop#201]
![Snipaste_2020-06-08_14-47-51](https://user-images.githubusercontent.com/47130297/84000379-1672ce80-a997-11ea-9647-f84bf5abbe08.png)

**Comment by Jermolene** [comment]
Hi @gyuezhang do you get the same problem if you open the wiki in a regular browser? If the problem isn't specific to TiddlyDesktop then you'll need to open a ticket at https://github.com/Jermolene/TiddyWiki5

**Comment by pmario** [comment]
Did you install a "read only" theme. There may be some CSS files active, that hides this stuff.

**Comment by gyuezhang** [comment]
I used a read-only theme that caused this problem, Thanks for replying
