### ISSUE TITLE
What does TiddlyDesktop use it's incoming network connections for?

### ISSUE THREAD

**Issue by Toontje** [Jermolene/TiddlyDesktop#205]
<img width="421" alt="Screenshot_2020-07-07 12 21 16_X9bFfn" src="https://user-images.githubusercontent.com/4884243/86767652-977fbd00-c04c-11ea-8145-7c749c056a80.png">

**Comment by Jermolene** [comment]
Hi @Toontje TiddlyDesktop uses incoming network connections when hosting TiddlyWiki folders (they are served over HTTP while single file wikis are accessed locally via a file:// URI). I don't think that nw.js itself does anything that accepts incoming connections but that might require further research.

**Comment by Toontje** [comment]
Ok, thanks.
