### ISSUE TITLE
Just a question

### ISSUE THREAD

**Issue by HiRolla** [Jermolene/TiddlyDesktop#229]
Hello! Is there any way to install [this chrome extension ](https://chrome.google.com/webstore/detail/paint-on-web-online-draw/ejllkedmklophclpgonojjkaliafeilj) into the bult in chrome engine?

I use my TiddlyWiki for live presentations and this extension allows me to point, draw and type during the presentation using hotkeys.  Thanks

**Comment by Jermolene** [comment]
Hi @HiRolla according [this discussion](https://groups.google.com/g/nwjs-general/c/40nlcCrLbwE) it should be possible to do so. You'll need to reach into the folder containing the TiddlyDesktop executable and make modifications to the `package.json` file
