### ISSUE TITLE
Add spell-checking support

### ISSUE THREAD

**Issue by DMLou** [Jermolene/TiddlyDesktop#32]
One nice thing about running TiddlyWiki in a full browser is that most of them have built-in spell checkers. It would be nice to have this same functionality in TiddlyDesktop as well.

**Comment by danielo515** [comment]
This is the only thing that keeps me using firefox instead of TiddlyDesktop. I understand that this is not a built in feature of NW.js and it could take time.

**Comment by pmario** [comment]
There are a lot of requests to include browser features into TiddlyDesktop. Which in the end means to build a browser. If you build a browser, you have to support it and more important make it secure. So in the end ... -> use a browser if you want the browser features.

**Comment by danielo515** [comment]
That sentence is unfair @pmario ,

Spell checking is a feature that makes a lot of sense in a tool that is meant to create content and write text. Microsoft word, notepad++, vi and other software about text writting has spell checking, and they are not browserts. We are not asking for implement bookmarks,navigation or other browser features, just spell checking.

**Comment by jekuno** [comment]
@danielo515 I think his comment is not meant to be unfair but more a general technical hint, see e.g. https://github.com/Jermolene/TiddlyDesktop/issues/21#issuecomment-111714753 for details.

**Comment by Jermolene** [comment]
The only ways that I can see being able to offer spell-checking within TiddlyDesktop are:

* That we migrate from nw.js to another framework that does support spell-checking
* That we integrate a JS library that does spell-checking. Googling suggests that there are some out there

Actually, another option might be a spell-check plugin for CodeMirror if such a thing exists.

**Comment by pmario** [comment]
>Spell checking is a feature that makes a lot of sense ...

Sure, every feature that a browser has, makes sense, for many users. It wouldn't be there, if not. ... The problem is, that spell checking done right is a project on its own. How many additional libraries (DLLs) do you need to install, that MSWord, Notepad++ or VI can do spell checking? Then multiply it by 3 for Windows, Linux, OS X ... 

... Do you think, we are able to support questions like this: 

>In the browser if I write [you name it] it is detected. Word and VI know it too. But TiddlyDesktop does not. 

As Jeremy wrote, it needs to be built into an existing framework, that we use. Doing it on our own is close to impossible, with the resources available. 

Eg: **"phonetic search" is only one aspect of spell checking**, that would also improve the TW search mechanism. 

**Word stemming is only one aspect of phonetic search.** .. To do word stemming you need a separate "configuration" file for every language you want to support. English is different to eg: German and Spanish. ... 

**noun detection is one more aspect** ... and so on ... 

IMO the existing open source libraries are not the problem. The problem is: Users are expecting a very high accuracy, because they are used to it. So we can't just  do "a little bit of spell checking" ... we would need to do it right.

just my 2 cents. 

see: 
 - https://github.com/NaturalNode/natural
 - https://en.wikipedia.org/wiki/Stemming

**Comment by Jermolene** [comment]
It turns out that just as we were discussing this issue nw.js added spell-checking support to the latest alpha:

https://groups.google.com/forum/m/#!msg/nwjs-general/c25l_jGMqj8/rsAtdSQuxeUJ

I'll wait until it's in the main branch before enabling it in TiddlyDesktop.

**Comment by danielo515** [comment]
That is surprising. Then we should disable it to not be using another browser.

**Comment by Jermolene** [comment]
Sorry @danielo515 I'm not sure what you mean? Are you not in favour of adding spell checking support to TiddlyDesktop?

**Comment by danielo515** [comment]
Hello @Jermolene ,

Yes I am in favor, definitively. I was just joking because this topic have been discussed several times, and many people seems to be against it because it is not a normal program feature.

Please forget about my stupid comment. Glad to see that we are going to have spell checking.

**Comment by jbardi** [comment]
I'm actually surprised it is even a requested feature. I am on a Mac, so I can't speak for Windows, but I have system wide spell check, even in browser fields and, yes, even in TiddlyDesktop, so not sure if this is a feature that should be app specific in this day and age. This is something that should be handled at a base level by the operating system. Again, not familiar with the current Windows features, but I can't imagine there isn't already a system wide spell check.

**Comment by DMLou** [comment]
Windows and Linux do not have system-wide spell check, even in browser fields, and even in TiddlyDesktop.

**Comment by mwchase** [comment]
I'm on a Mac and it seems like Apple programs have one spell check, Chrome has another that superficially resembles it, and TiddlyDesktop has nothing at all. How did you get it working?

**Comment by mwchase** [comment]
It looks like NW.js is several versions along from 0.13. Has anyone tried building TiddlyDesktop with a newer version, and enabling spellcheck?

**Comment by yzaretskiy** [comment]
Any updates on the spell check feature?

**Comment by ParoTheParrot** [comment]
> Any updates on the spell check feature?

**Comment by sid-thakur** [comment]
> Any updates on the spell check feature?

Thanks!

**Comment by HuwJanus** [comment]
Just a little workaround for you all:
In the Tiddlydesktop folder is the package.json file.
Open it in you favorite text editor and find the following line:
`"chromium-args": "--mixed-context"`

change it to:
`"chromium-args": "--mixed-context --enable-spell-checking"`

Off you go - spell checking should now be enabled in any tiddlywiki file that you open with TiddylDesktop.

**Comment by BurningTreeC** [comment]
Hi @HuwJanus , your solution works, thanks! It could probably be a pull request, I think it's the easiest way to enable spell-checking

**Comment by Jermolene** [comment]
Hi @HuwJanus that's great thank you, I had no idea it was so simple.

I tested it with my wifi disabled and spell checking still occurs, so we can be confident that it is not using an online service.

**Comment by HuwJanus** [comment]
The chromium-args are based on the Chrome engine that node is using, and the spell check argument simply enables the built in spell checker that comes by default with the Chrome browser. Once enabled TiddlyDesktop has spell checking enabled _as does any window that it subsequently opens_, and that means our TiddlyWiki files have a fully functional spell checker built in just as if they were being opened in a browser window.

Its a handy command to remember if you develop node apps and as we see, any node app where we can directly edit the package.json file can have spell checking turned on.

All good stuff! :)

**Comment by jakob1111** [comment]
How is it possible to turn the spellchecking off or change the language? For some reason, all text is marked red for me. I already changed my OS language to English and tried to change all Chromium flags that seemed relevant.

**Comment by pdroalves** [comment]
I'm not sure this fix is really working. As @jakob1111 , all text is marked red for me when --enable-spell-checking is used.

**Comment by MoritzB90** [comment]
Hi @jakob1111, I have had the same issue and come up with a workaround, which is not pretty but seems to work. If you first start TiddlyDesktop a new directory called 'Dictionaries' is created, which contains a .bdic dictionary file. In my case 'de-DE-3-0.bdic' for the German language. However, I also wanted to have the spell checking in English, not German. Unfortunately, I could not yet figure out how to set the language manually. As you already stated, simply changing the OS language did not work. However, one can download a different .bdic dictionary, e.g. 'en-US-3-0.bdic', from [https://github.com/cvsuser-chromium/third_party_hunspell_dictionaries](https://github.com/cvsuser-chromium/third_party_hunspell_dictionaries). Just place the new .bdic dictionary inside the TiddlyDesktop 'Dictionaries' directory. Next, you will need to change the name from 'en-US-3-0' to whatever was the default before (in my case 'de-DE-3-0). This will trick TiddlyDesktop into using the english dictionary for spell checking. As I have said, this solution is not very pretty so it would be nice to hear if anyone has come up with a better way to manually set the language for spell checking.

**Comment by Takiro** [comment]
Did anyone figure out how to change dictionary language without the hacky workaround of renaming dictionary files? I don't want to restart TiddlyDesktop every time. Despite having multiple dictionaries in the Folder, the "Change Language" option from the normal Chromium context menu is missing.
