### ISSUE TITLE
Spaces in pathname disrupts import features

### ISSUE THREAD

**Issue by braykov** [Jermolene/TiddlyDesktop#35]
Nothing happens when I try to import files from my PC.
The green ribbon on the top shows up, but after I drop the items, the $:/Import tiddler doesn't open.
I have also tried via Tools->Import - again, nothing.

However, pasting text with CTRL+V works. Drag/Drop tiddlers from another wiki also works.

Tested with version 5.0.16

**Comment by Jermolene** [comment]
This was fixed in v0.0.6
