### ISSUE TITLE
Reaveal Backup Folder for a wiki located on a mapped network drive

### ISSUE THREAD

**Issue by braykov** [Jermolene/TiddlyDesktop#50]
This is Windows 64bit.
I have opened a wiki file which is located on my mapped network drive - O:
When I click the button, I get an error message saying:
Windows cannot find 'C:\O:\Wikis\mywiki.html_backup'. Make sure you typed the name correctly, and then try again.

**Comment by neocult-de** [comment]
This also occurs on local drives.if the drive the wiki is on, is not C:. Absolute pathes work correct on other drives, if set in the Control panel. So relative pathes on Windows seem buggy. (tested on tiddlydesktop-win64-0.0.4)
