### ISSUE TITLE
v0.0.4 issues with node-webkit Windows build

### ISSUE THREAD

**Issue by Eucaly** [Jermolene/TiddlyDesktop#52]
* Issue 1, hang when opening *.html wiki, seems freeze while taking TiddlyWiki window snapshot => happen for 0.11.4, 0.11.5
* Issue 2, nw.exe process still running in background after closing TiddlyDesktop main window, blocking the next execution of TiddlyDesktop. Work-around is to terminate the nw.exe process with TaskMgr => happen for 0.8.4, 0.10.5, 0.11.4, 0.11.5
* Tested node-webkit versions: as listed above (Windows build)

**Comment by Jermolene** [comment]
I think this is fixed in 56892f66d5860974a47022d9e77df552087501a8. I'll issue v0.0.5 soon, but if anybody has the chance to try their own build please let me know if it works for you.

**Comment by Jermolene** [comment]
Closing as fixed in v0.0.6

**Comment by stgaup** [comment]
I have this issue on version 0.0.8 on Windows 10.
When I open the program, it is only shown on the taskbar.
When I hover over the app on the taskbar, the preview thumbnail is shown.
When I click the thumbnail nothing happens.
When I right-click and then select Maximize the window is shown.
But when I click the "Restore" button, the window is minimized back into the taskbar.
So essentially it is impossible to have a window that is covering less than the full screen, which is quite annoying.

**Comment by istvank** [comment]
@stgaup this is covered in #83 and #98. Solution is to maximize, then drag & drop the title bar downwards.

**Comment by stgaup** [comment]
Ok, thanks, I will try. It worked! Thanks!
