### ISSUE TITLE
Proposition to add td releases to tw.com

### ISSUE THREAD

**Issue by Spangenhelm** [Jermolene/TiddlyDesktop#54]
Hi, don't you think that tiddlydesktop's releases deserves a place on tw main site, maybe by adding a tab to the "release" tiddler ? (see exemple below)

![capture du 2015-01-16 16 38 41](https://cloud.githubusercontent.com/assets/6536752/5778801/27f30892-9d9e-11e4-88e0-0814ab598a1e.png)

**Comment by demiurg888** [comment]
Hello!

To date, I have not yet figured out your program. If you could advise me -
I would appreciate it.

2015-01-16 18:43 GMT+03:00 Florent V. <notifications@github.com>:

**Comment by Spangenhelm** [comment]
Sure!
If you go to: http://tiddlywiki.com/#Releases you can find all releases(versions) of tiddlywiki and i think [tiddlydesktop releases](https://github.com/Jermolene/TiddlyDesktop/releases) should be mentionned on it too, to do this i suggest to add a tab (like the ones at the beginning in the picture above, which is a example i have just made for illustration) it would allow us to "switch" from tw to td releases. I hope it help you understand because i have no idea on how to explain it differently ;-)

**Comment by Jermolene** [comment]
@Spangenhelm that's a good idea, would you be willing to do a pull request?

**Comment by Jermolene** [comment]
@Spangenhelm I meant a pull request to https://github.com/Jermolene/TiddlyWiki5

**Comment by Spangenhelm** [comment]
Yes, no problem. Here is what i plan:

1. We create a new tid that will handle the tw and td tabs (we can call it "Releases", see below)
2. The old "Releases" tid should be renamed (eg: "TiddlyWiki Releases" because this one will contain only tw rel)
3. We create a new tid and name it for example: "TiddlyDesktop Releases" (same reasons as above)
4. We create 4 new tid that will handle the different versions released (as of now for tw)
5. To prevent the "release" term to appear everywhere we could use captions and reduce the titles, like this we could have tabs named `TiddyWiki` and `TiddyDesktop`

If you agree i will still have to let you create the new tiddlers for the releases (because i don't know how to create them, where to create them, how to name them and what to write in them.. ;-P )

**Comment by Jermolene** [comment]
Hi @Spangenhelm that sounds exactly right. We'd also need to import the release notes for the existing releases of TiddlyDesktop.

Are you new to both pull requests and running TW under Node.js?

**Comment by Spangenhelm** [comment]
> Are you new to both pull requests and running TW under Node.js?

Well i have done a few pull requests but never ran tw under node.js.. is it needed here?

**Comment by Jermolene** [comment]
Hi @Spangenhelm 

> Well i have done a few pull requests but never ran tw under node.js.. is it needed here?

Node.js can be avoided for small docs changes, but if you want to see the results of your pull request before you submit it then you'll need to fork the TW5 repo, make your modes, use Node.js to rebuild the .html files, review them, and then go to github.com to create a pull request from the fork.

It would definitely require a bit of an upfront investment but it would put you in a good position for making future improvements, too.

**Comment by Spangenhelm** [comment]
Thanks for the explanation, i have just installed node and it is working fine.
About forking and building my own tw i have looked a bit in the docs and the dev edition but i have not found exactly what i need, can you point me to the right direction ? I need to download your repo in zip then use the `test` script to build tw ?

**Comment by Jermolene** [comment]
Hi @Spangenhelm sorry for the late response. See http://tiddlywiki.com/#Working%20with%20the%20TiddlyWiki5%20repository

Once those steps are performed then you can build TiddlyWiki with this command run from the root of your fork:

```
tiddlywiki editions/tw5.com --build index
```

Then you'll find the index.html in `editions/tw5.com/output`.

**Comment by Spangenhelm** [comment]
Hi @Jermolene, i have tried to follow your instructions but:

The link you gave me says:
"3. Clone a local copy of your fork" how do we do it ? is it downloading a copy in zip ?
I have tried but if i download my fork then i am working on a old version (5.1.6 which was the version back when i have forked the main repo) it does not seem logical to use a fork instead of your repo..

Also what is the point of the `sudo npm link` ? (because the doc says: "After this procedure you can work with TiddlyWiki5 via npm as though it were installed in the usual way with npm install -g tiddlywiki.") so why not installing the otherway ?

At last when all is done and that i try to launch it with "tiddlywiki --server" with the right working directory the terminal report an error: "Warning: Wiki folder '/home/TiddlyWiki' does not exist or is missing a tiddlywiki.info file"

I have also tried: "tiddlywiki editions/tw5.com --build index" and the files are created ok but then i have no idea what to do next, how to work with it ?

Thank you for helping me helping you ;-)

**Comment by Spangenhelm** [comment]
Edit: i think it might be a good idea to add the pre-release version too (of course with a warning to not use in production) the advantage is that it allow the user to follow the evolution of tw, we know what is going on and what is coming up, a little like the roadmap but in live !

About the `tiddlywiki editions/tw5.com --build index` it is for merging every portion to a single file, like a compilation i guess ?

I still couldn't figure out how to work with node. Thank you

**Comment by Jermolene** [comment]
>  it does not seem logical to use a fork instead of your repo..

The purpose of using a fork is so that you can make changes and share them back via github.

> but if i download my fork then i am working on a old version (5.1.6 which was the version back when i have forked the main repo) 

You need to rebase your fork. If it doesn't have any important modifications I think you can get away with deleting it and recreating it.

> Also what is the point of the sudo npm link ? 

It's so that npm uses your development copy of TW when you call "tiddlywiki" on the command line.

> At last when all is done and that i try to launch it with "tiddlywiki --server" with the right working directory the terminal report an error: "Warning: Wiki folder '/home/TiddlyWiki' does not exist or is missing a tiddlywiki.info file"

Did you initialise the wiki folder with the `--init` command?

> Edit: i think it might be a good idea to add the pre-release version too

Good idea. We have a temporary issue that makes it impossible to update the text of tiddlywiki.com until 5.1.8 is released.

> About the tiddlywiki editions/tw5.com --build index it is for merging every portion to a single file, like a compilation i guess ?

It's the command that I use to turn the loose tiddlers that you see in editions/tw5.com into the HTML file at http://tiddlywiki.com/index.html.

**Comment by Spangenhelm** [comment]
Hi @Jermolene thank you for the answers.

>share them back via github..

So i guess i need to install `git` to be able to "push" the modification back to my fork and transform them into pull-requests that you can merge in your repositery ?

The dev docs are not talking about git except for publishing plugins..

**Comment by Jermolene** [comment]
> So i guess i need to install git to be able to "push" the modification back to my fork and transform them into pull-requests that you can merge in your repositery ?

That's correct, yes.

> The dev docs are not talking about git except for publishing plugins..

Pull requests for improvements welcome!

**Comment by Spangenhelm** [comment]
> Pull requests for improvements welcome!

:ok_hand:

**Comment by Spangenhelm** [comment]
>Pull requests for improvements welcome!

Hi @Jermolene unfortunatly i have got too much trouble on my side and i am too new to this to propose a improvement this time, i am afraid that we will need someone experimented with git, node and pull requests to do so..

**Comment by Spangenhelm** [comment]
@Jermolene do you know someone who might be interested with giving a little help here ? Thanks

**Comment by Jermolene** [comment]
Hi @Spangenhelm there are some videos from @pmario that may be helpful. There's a lot of general material about git out there that's not TiddlyWiki specific; easy to Google once one knows the vague vocabulary.

**Comment by Spangenhelm** [comment]
Hi @Jermolene, 
You are right but the problem here is that there were things i did not understand that are tiddlywiki specific, for example to have a working copy that can autosave with node.js (here the tw5.com edition) i have had to do:
`tiddlywiki MyFolder --init tw5.com` then if i do `tiddlywiki MyFolder --server` it won't autosave (don't know why), worst: it forces the browser to put all in one file, like the usual save, which is uncompatible with the need to keep everything splitted in the folder for git push. So what i have done is that i have modified the `tiddlywiki.info` file to include `tiddlywiki/tiddlyweb, tiddlywiki/filesystem` into the "plugin" section in order for this work as i expected(to figure this out took me forever as there are no mention of them anywhere). I have spend so much time trying to figure what does what and why, it is really a pain and i clearly still don't know what i am doing.

I'll take a look at this later and do my best to improve the docs for other users.
+

**Comment by Jermolene** [comment]
Hi @Spangenhelm the problem here is (as you've discovered) that you started with the `tw5.com` edition, which lacks the components needed for the client-server configuration. The `tw5.com-server` edition is provided that includes both the `tw5.com` content and the necessary plugins. The preferred fix is https://github.com/Jermolene/TiddlyWiki5/issues/1011

**Comment by Spangenhelm** [comment]
@Jermolene there is a little problem: apparently the `tw5.com-server` edition comes empty...

**Comment by Jermolene** [comment]
Hi @Spangenhelm indeed, the `tw5.com-server` edition uses the `includeWikis` field in it's `tiddlywiki.info` file to include the content directly from the `tw5.com` edition. So you're probably better off cloning the `tw5.com` edition and then editing the `tiddlywiki.info` file to add the two plugins that are needed for client-server operation.

**Comment by Spangenhelm** [comment]
Ok, then that is what i will add as an explanation for the docs (what is better to include: the main site or the dev site or both ? The issue if we do both would be to keep them "synchronised" (if we modify one we need to think of updating the other too, otherwise we will get lost)
Because only a few people will ever need it then i suggest to only talk about it in the dev docs. (what about deleting the referencies on the main site to keep it clean ?)

**Comment by Jermolene** [comment]
Thanks @Spangenhelm. I guess the topic here is "How to enable a wiki folder for client-server usage", covering the adjustments to `tiddlywiki.info`, perhaps using `tw5.com` as an example. Plus some appropriate links from other topics.

Generally, the line between the main site and the dev site is whether the material is targeted at JavaScript developers. Stuff about using TW under Node.js should go in the main site unless it's related to development.

**Comment by Spangenhelm** [comment]
Thanks for the explanations, about the `tw5.com` edition: should not we get rid of the `5` in it (after all it does not make sense anymore and it is more confusing than anything)

**Comment by Spangenhelm** [comment]
Edit: this morning i have been working on the improvements we have talked about and a problem showed up: i have modified an already existing tiddler because i needed to (`Installing TiddlyWiki on Node.js`) that i have got straight from the fork of your repo, the problem is that i have used the version of the `tw5.com` edition and it is not the most recent, the most recent being the one from the prerelease version, so what should i do ? if i work with the tw's version then there is a chance that it might be outdated, creating conflicts and if i work with the pre-release it may causes issues too no ? The changes i have made are pretty small so i guess i could also pass directly from github versions but i wanted to be sure of the results before publishing so it is not practical, last possibility: i modify what i need on my side and then i update the github version, once again i feel like it is not practical.
Any advice ?
Thank you

**Comment by Jermolene** [comment]
Hi @Spangenhelm apologies for the late response.

Ideally, your modifications should be based off of the "master" branch, which gets posted to tw.com/prerelease. But I'm sure we can fix up any difficulties.

**Comment by Spangenhelm** [comment]
Hi @Jermolene this is what i did: delete my old fork, refork yours so it is up to date and work on the master branch. so i guess i should work on the "prerelease" edition the next time, instead of the tw5.com, just to be sure that i work with the very last versions of each file.

**Comment by Jermolene** [comment]
Hi @Spangenhelm the prerelease edition includes the tw5.com content, plus some specific tiddlers such as the ones you see in default tiddlers. So most content edits should go to the master branch in the editions/tw5.com folder.

**Comment by Spangenhelm** [comment]
Hi @Jermolene 
> So most content edits should go to the master branch in the editions/tw5.com folder.

Sorry but i dont understand, if i use the master branch of the tw5.com edition then some tiddlers are not the very last ones (the very last are the one of the pre-release version) for example:

There is a part about 'debian' present in the `Installing TiddlyWiki on Node.js` on the pre-release version that is not yet present in the same tiddler of the tw5.com edition. So modifying the actual one is not good.

**Comment by Jermolene** [comment]
The master branch of the content in `editions/tw5.com` corresponds to the latest prerelease. Anything you see in the prerelease snapshot at http://tiddlywiki.com/prerelease should be present in the master branch.

**Comment by Spangenhelm** [comment]
I don't know what happend but you are right, thanks.
