### ISSUE TITLE
My wiki file used to open but now doesn't

### ISSUE THREAD

**Issue by ittayd** [Jermolene/TiddlyDesktop#57]
Not sure what happened but now when I launch TiddlyDesktop and open my tiddly file, it doesn't open. The taskbar shows there is a second window, but it doesn't appear when I click the taskbar icon. I've closed the main window, killed the nw processes, deleted the folder from which I ran and extracted again from the zip, removed and added the file. Nothing helps. It used to work perfectly in the past. Also, the file does open fine in Chrome.

**Comment by ittayd** [comment]
I just found a workaround. From Process Explorer, I choose the top nw.exe process, then windows->maximize. This made the window appear (bring to front didn't help)

**Comment by Jermolene** [comment]
Hi @ittayd apologies for the delayed response. I'll release a new version of TiddlyDesktop soon that fixes the phantom process issue.

**Comment by ittayd** [comment]
I now in a situation that the top nw.exe process also doesn't have an associated window. 0.0.4 doesn't work either. Please see https://github.com/Jermolene/TiddlyDesktop/issues/65

**Comment by Jermolene** [comment]
I think the phantom process issue is fixed in 56892f6. I'll issue v0.0.5 soon, but if anybody has the chance to try their own build please let me know if it works for you.

**Comment by Jermolene** [comment]
Closing as fixed in v0.0.6
