### ISSUE TITLE
Windows version: multiple links to same TW

### ISSUE THREAD

**Issue by GiggliG** [Jermolene/TiddlyDesktop#59]
I've noticed that after opening and saving a TW, frequently I'll end up with two copies of the same TW in the TiddlyDesktop launcher.

This happens with files that have spaces in the names. I'll have one copy of the file with spaces, and another copy with the spaces replaced by "%20".

**Comment by Jermolene** [comment]
Hi @GiggliG thanks for the report, I'll investigate. I assume you're using the latest 0.0.4 version of TiddlyDesktop?

**Comment by GiggliG** [comment]
Good question. I;m not 100% sure if I installed 0.4 or was put off by the warning and installed 0.3 instead. I don't see a version number anywhere. Is there a way to identify the version I'm running?

**Comment by Jermolene** [comment]
Hi @GiggliG there was a bug with pathnames containing spaces in 0.0.3. You can find out the version you're using with the About menu item. I'd advise moving to 0.0.4; it's been out for a long time now, and is definitely more stable than 0.0.3.

**Comment by GiggliG** [comment]
Okay, I'll try it and report back. For the record, there's no about menu in the version I'm running. Here's what it looks like:
![image](https://cloud.githubusercontent.com/assets/10089419/7912607/ed7633b4-0860-11e5-91ae-f3b86933b580.png)

**Comment by GiggliG** [comment]
Okay, I've updated - I was running 0.0.3.

The new version doesn't have an About menu either:
![image](https://cloud.githubusercontent.com/assets/10089419/7912709/c6fd836c-0861-11e5-99f8-1fe7b7b825b1.png)

**Comment by Jermolene** [comment]
> The new version doesn't have an About menu either:

Apologies, for some reason I was thinking you were on the Mac, despite you clearly stating you were on Windows.

**Comment by Jermolene** [comment]
Hi @GiggliG this was fixed in v0.0.6
