### ISSUE TITLE
Version 0.0.4 slow window resize problem

### ISSUE THREAD

**Issue by GiggliG** [Jermolene/TiddlyDesktop#60]
I've been using 0.0.3, and have just updated to 0.0.4 and have noticed it is *really* slow to resize windows.
The firstt ime i ran it, I opened a TW, dragged the window to resize, and the frame expanded, but the TW stayed the same size, leaving black borders all around it. And then it stopped responding for over a minite and i had to force close it in task manager.

Then I opened it again, and this time windows resized, but with a very noticeable lag, ranging from about a second to over 30 seconds. During this time both the specific TW and the nw.exe launcher are completely unresponsive.

I'm on windows 7, x64. Is this a known issue and is there a fix?

**Comment by Jermolene** [comment]
Thanks @GiggliG, that's helpful. I hope to do another release of TiddlyDesktop over the next few weeks, and will address this issue.

**Comment by GiggliG** [comment]
I've found that when it locks up like this, one of the nw.exe's is using up one CPU core at 100%. It seems to happen not just when i resize a TW instance, but also when i just drag the TW window around in windows.

I hope you have a fix coming soon, it makes it very hard to use if I just have to stop and wait for several minutes at unpredictable times.

**Comment by Jermolene** [comment]
Hi @GiggliG this was fixed in v0.0.6
