### ISSUE TITLE
Tiddlydesktop 

### ISSUE THREAD

**Issue by NimajnebNhoj** [Jermolene/TiddlyDesktop#63]
Tiddlydesktop for Windows 8.1 ( 64-bit) doesn't run after I've downloaded and extracted from zip folder. I click on nw.exe application and nothing happens.

**Comment by Jermolene** [comment]
Hi @NimajnebNhoj 

Can you see nw.exe in the process list of Windows Task Manager?

**Comment by NimajnebNhoj** [comment]
Hi Jeremy -

No I can't see NW in the processes list of Windows Task Manager. I have
since started using Notestorm which I find easier to get around.

As a novice at TW I'm finding that I have to spend a lot of time
understanding/processing instructions. As with a lot of things the more you
try the easier it becomes .......sometimes!!

 Thanks for getting back

Ben

**Comment by Jermolene** [comment]
Hi @NimajnebNhoj glad you're up and running. There'll be a new release of TiddlyDesktop soon and I hope you'll give it a try.
