### ISSUE TITLE
Application Bugging

### ISSUE THREAD

**Issue by bloodnines** [Jermolene/TiddlyDesktop#64]
When opening the TiddlyWiki Desktop application on my Mac using Yosemite 10.10.3, the application window opens quickly, and is completely white. It then follows up too Hide the application window and the whole thing becomes unresponsive to any interaction, requiring it too be being force closed.

It was running perfectly fine until a while ago. About a week.

**Comment by Jermolene** [comment]
It may be worth trying deleting the TiddlyDesktop's configuration data.

* In Finder, click the Go menu with the option key pressed, and choose Library
* Navigate into the "Application Support" folder
* Locate and delete the "TiddlyWiki" folder

Does that help?

**Comment by bloodnines** [comment]
This worked perfectly. Thank you very much for your timely response :)

**Comment by Jermolene** [comment]
Great, glad you're up and running @bloodnines
