### ISSUE TITLE
Cannot Delete Tiddlers on Linux 64 bit

### ISSUE THREAD

**Issue by mklauber** [Jermolene/TiddlyDesktop#66]
Clicking the trash can during edit mode does not seem to delete the tiddler. 

I think it's related to https://github.com/nwjs/nw.js/issues/2683

Essentially, before version nw12, there is a bug in nw.js that prevents the alert and confirm dialog from displaying.  Instead they always return immediately, with the confirm dialog at least returning false.  As you might expect, this makes it difficult to delete tiddlers.  Not sure how to fix this besides updating the version of nw.js that tiddlyDesktop is built on, and I'm sure that's not a simple easy thing to do.  

Anyway, just wanted to give you a heads up and add the info I'd determined.  If you need someone to test a fix at some point, let me know and I may be able to help.

**Comment by Jermolene** [comment]
Hi @mklauber apologies for the very slow response. I'll do an update to TiddlyDesktop including an upgrade of nw.js as soon as I can.

**Comment by mklauber** [comment]
Just as a FYI, I managed to build this with nwjs-v0.12.3 (with minor changes to the build script) and can confirm that this bug is fixed with the new version.

**Comment by Jermolene** [comment]
Hi @mklauber I'm preparing a v0.0.5 update that is based on nw.js v0.12.3. I'd appreciate any feedback if you're able to build and test the master branch. Thanks!

**Comment by mklauber** [comment]
Built Successfully, seems to be working (I could build everything, but only tested it on linux x64, as that's what my machine is.).  Also, appears that https://github.com/Jermolene/TiddlyDesktop/issues/65 is fixed in this build as well.

**Comment by mklauber** [comment]
As soon as it's released, feel free to close this bug.

**Comment by Jermolene** [comment]
Thanks @mklauber, much appreciated.
