### ISSUE TITLE
Use relative paths for files in the AppData folder

### ISSUE THREAD

**Issue by Jermolene** [Jermolene/TiddlyDesktop#68]
See comment https://github.com/Jermolene/TiddlyDesktop/issues/65#issuecomment-150919866:

> I think the problem is that you are storing absolute rather than relative paths in files in the AppData folder. This means if the folder containing TiddlyDesktop is renamed things break. It should be possible to store these paths relative to the folder from which nw.exe is executed to make this more robust.

**Comment by JohnHind** [comment]
Just to add to this, if there is something that prevents the main window appearing, it ought to show an error dialog instead and then exit cleanly. Even when you use the relative paths, something else could go wrong with the settings folder.

**Comment by jekuno** [comment]
:+1:

**Comment by Jermolene** [comment]
So there are several things to do:

* Add a check for a broken `includeWikis` link, and display a message and fix it
* Restructure the `includeWikis` mechanism so that an absolute link isn't required. The problem here is that we can't use a relative link, because they would also break if the app was moved. The best solution is probably not to use `includeWikis` at all, but to have the TiddlyDesktop startup code in `main.js` inject the necessary tiddlers during the boot process. Given that the included wiki only contains the TiddlyDesktop plugin, it may be possible to simplify things further
* Add an error handler that can trap errors during startup (it's going to be quite tricky to catch errors correctly within asynchronous code)
