### ISSUE TITLE
Disable Backups

### ISSUE THREAD

**Issue by eliduenisch** [Jermolene/TiddlyDesktop#75]
Hi, is it possible to disable the backup feature? The desktop application ignores the settings in the tiddlywiki-file and produces a unique backup copy each time the file has been changed. This leads to accumulation of quite a lot of files.

**Comment by Spangenhelm** [comment]
+1 ! Related to my previous thread: https://github.com/Jermolene/TiddlyDesktop/issues/58

I have just downloaded the new version of td (v0.0.6) but still no way to disable or at least limit the number of copies saved of our tw's so in this configuration it is not practical at all with a cloud provider ( only one tiny modification = one upload of the whole file = waste of bandwith and space = what is the point ? is there someone who need to keep __unlimited__ copies of a file ? )

**Comment by eliduenisch** [comment]
Hi Spangenheim, thank you for your comment on this. I also use cloud sync (owncloud) and TW5 file size starts at 1.4 MB, so syncing all the time creates some traffic. One work around would be to set the backup directory to some folder that is not beeing monitored by the sync client.

**Comment by Spangenhelm** [comment]
> One work around would be to set the backup directory to some folder that is not beeing monitored by the sync client.

Yes you can and you know that by doing this you lose the automatic side of the backups and the risk of losing datas increase.. so i would rather completly disable the backup system and use an "external" solution such as Time Machine or Back In Time or whatever software that you can control and set-up to meet your needs.

I wonder how do the others do ? I am glad that i'm not the only one concerned ;-)
++

**Comment by jbardi** [comment]
I had to setup a 3rd party monitoring app that runs a script to check the number of files in the backup folder and to drop off older ones so that I only have a max of 5 backups. It is sad that I have to resort to a 3rd party solution because the app itself has no limits on the number of backups.

Don't want to give us the option to turn it off? Then at least let us choose the number of maximum backups and have TiddlyWiki monitor the folder for me. If you don't think it is your responsibility to keep my backup folder clean, then it is also not your responsibility to force us to do backups in the first place. Pick an option, one or the other, but you can't have both!

**Comment by somenxavier** [comment]
Related to this feature, perhaps you could also put a *limit* on number of copies.

**Comment by TheBashar** [comment]
I too would appreciate the option to disable the backups. My tiddlywiki is synced with dropbox which provides all the previous revision retention that I need.

**Comment by KithorasCarzyl** [comment]
Experimented for 2 minutes and found a very easy shortcut to disable the backups:

1. Locate the installation folder of you TiddlyDesktop (e.g. `C:\Program Files\TiddlyDesktop`)
2. Locate the subfolder `js\utils`
3. Open the file `saving.js` with any text editor
4. Comment out the lines 30-32 with `//` before each line (In fact you need only to comment out line 31 like this: `// backupFile(filepath);` )
5. Save the file

Now if you save any file the backups are disabled.
👍

**Comment by somenxavier** [comment]
[This] is related to this issue

**Comment by jezhill** [comment]
@KithorasCarzyl  has the right idea.   The next step in that evolution would be to let the app retain the ability to make backups in general, but to make it respect a wiki-by-wiki preference.  

My approach has been to allow either a blank string or `"/dev/null"` to signify a preference for no backups. I  hacked `saving.js` (in my case, on OSX, that's `TiddlyDesktop.app/Contents/Resources/app.nw/js/utils/saving.js`) as follows:

```
--- a/saving.js
+++ b/saving.js
@@ -80,2 +80,3 @@
 			backupSubPath = backupPathByPath(filepath);
+		if(backupSubPath == "" || backupSubPath == "/dev/null"){ return; }
 		// Compose and uniquify the backup pathname
@@ -103,2 +104,3 @@
 		backupPath = $tw.wiki.getTiddlerText("$:/TiddlyDesktop/BackupPath","");
+	if(backupPath == "" || backupPath == "/dev/null"){ return backupPath; }
 	// Replace $filename$ with the filename portion of the filepath and $filepath$ with the entire filepath 
```

**Comment by Jermolene** [comment]
I've added the ability to disable backups on an individual wiki basis for v0.0.12. Commits coming up.
