### ISSUE TITLE
Nothing Happens on Windows

### ISSUE THREAD

**Issue by GiggliG** [Jermolene/TiddlyDesktop#80]
I've recently updated, and today I tried to run tiddly desktop, and in task manager, i see four nw.exe processes, but no TiddlyDesktop or Tiddlywiki windows appear.

I'm on Win7 64bit.

**Comment by Jermolene** [comment]
Hi @GiggliG you may have the problem described in #77. If so, the following steps should clear the problem:

* First, you’ll need to quit the application. That may be difficult if it has crashed; at worst, you can reboot your PC to make sure that TiddlyDesktop is not running
* Then, the configuration folder will be found at a path like: `C:\Users\Jeremy\AppData\Local\TiddlyWiki`
* Delete the entire folder “TiddlyWiki”, and all of its content
* Finally, re-run nw.exe

**Comment by GiggliG** [comment]
That worked (though it's a shame I lost all the TW's I had stored on it). Thanks for the fix!

**Comment by Jermolene** [comment]
You shouldn't have lost the actual TiddlyWiki's, just the record of them in the listing. You can re-add them by drag and drop

**Comment by akiy502** [comment]
@GiggliG
In my case, right-clicking on the showed frame > maximaze made TD appeared. Then drug-and-drop the title bar enable to change the size of minimized window.
