### ISSUE TITLE
v.0.0.6 - Mac - Stuck Fullscreen 

### ISSUE THREAD

**Issue by chris2fr** [Jermolene/TiddlyDesktop#81]
**Steps to Reproduce:**

1. Open either the list of wikis or one wiki in particular
2. Maximize to full screen

**Desired Outcome:**

1. Ability to unfullscreen by press of green button
2. Ability to unfullscreen by CMD F 
3. Ability to unfullscreen by ESC

**Actual Outcome:**

1. The Green Button is Under the Titlebar and Not Available
2. CMD F nor ESC do not help

**Environment**

Mac OS X El Capitan
TiddlyDesktop v.0.0.6 64 bits

**Comment by chris2fr** [comment]
Note. This was also mentioned by another user on the mailing list.

https://groups.google.com/d/msg/tiddlywiki/YKgoU635xPg/sQcM50_KBgAJ

> Also, when dragging TiddlyDesktop over onto to my second monitor it will sometime snap itself where the drag bar is underneath the toolbar.  So if I want to move TIddlyDesktop somewhere else, I end up having to close it down and delete the data under /Library/ so that I have a fresh start.  Normally under the Window selection you have a zoom -- that's not available here unfortunately.

The author speaks of deleting data under /Library/, but I cannot find the data in question.

**Comment by Jermolene** [comment]
Thanks @chris2fr this was actually fixed in v0.0.7
