### ISSUE TITLE
Main window won't show up

### ISSUE THREAD

**Issue by processo** [Jermolene/TiddlyDesktop#83]
After using TiddlyDesktop a few times the main window won't show up at start, but I can see it on the taskbar and (in v0.0.8) on the tray. It happened with v0.0.6 before twice, now it happens quite frequently.

Deleting `Users/[username]/AppData/Local/TiddlyDesktop` solves the problem temporarily.

**Comment by Jermolene** [comment]
Hi @processo thanks! Can you try two things:

1. Try running the TiddlyDesktop's nw.exe from the command line; you should be able to see any error messages that are generated as it starts up
2. If you like, you can send me a zipped up copy of the faulty AppData folder to analyse - there's no private data stored there beyond the pathnames and favicons of your wikis. My email address is jeremy (at) jermolene (dot) com.

**Comment by processo** [comment]
I ran `nw.exe` from command line, but gave no errors.

But I found the following in `$__TiddlyDesktop_Config_layout_backstage___WikiListWindow.tid`. **Note the -32000 values of window position.**
```
created: 20151230195419196
modified: 20151230205930171
title: $:/TiddlyDesktop/Config/layout/backstage://WikiListWindow
type: application/json

{
    "state": "minimized",
    "x": -32000,
    "y": -32000,
    "width": 800,
    "height": 600
}
```

After changing the values manually to `0` it works fine.

**Comment by Jermolene** [comment]
Thanks @processo, I'm investigating.

**Comment by processo** [comment]
Thanks. In the meantime for those who need a quick & dirty fix:
1. write the right position values in `$__TiddlyDesktop_Config_layout_backstage___WikiListWindow.tid`
2. make it **read-only**

**Comment by martyh1** [comment]
I ran into this and figured the window was off screen.  A trick I've used for this in the past for this sort of problem is to 1) click on the window from the task bar (still can't see window), 2) click alt-space on keyboard to bring up window menu, 3) type 'm' to move window, 4) hit right arrow key on keyboard, 5) move window around using mouse.  You might need to 'restore' window first from the window menu.

**Comment by processo** [comment]
@martyh1 Although I had no problems with the size, manually setting `width` and `height` should take care of that too (until it gets fixed).

**Comment by zielot** [comment]
I have the same problem as the others - somewhat annoying but not enough to invalidate the usefulness of this app (I have a bunch of heavy legacy TiddlyWiki files). I used martyh1's work-around but it's tedious. processo's work-around worked for me - once I managed to do it correctly.

**processo's work-around:**
1) go to  Settings > Open user config folder
2) open "user-config-tiddlywiki" folder
3) open the "tiddlers" folder
4) edit $__TiddlyDesktop_Config_WikiListWindow.tid:
`
title: $:/TiddlyDesktop/Config/WikiListWindow
type: application/json

{
    "state": "minimized",
    "x": 0,
    "y": 0,
    "width": 800,
    "height": 600
}
`

**Comment by begin-again** [comment]
I've been having this same issue with the wiki windows themselves. I found `$__TiddlyDesktop_Config_layout_wikifile___<<path and name of wiki>>` file and adjusted the x/y values. Set a read-only attribute for each wiki. Windows now open properly every time.

**Comment by andy-twosticks** [comment]
Yep, this is a problem for me too.  Processo's workaround .... works (around).

**Comment by Jermolene** [comment]
There's a new release of TiddlyDesktop that should address this issue:

https://github.com/Jermolene/TiddlyDesktop/releases/tag/v0.0.9
