### ISSUE TITLE
Make internal PDF viewable

### ISSUE THREAD

**Issue by mmohr007** [Jermolene/TiddlyDesktop#89]
Right now "Couldn't load plug-in" is shown when opening a Tiddler with a imported internal PDF (content type application/pdf) that is viewable without any problem in a normal TiddlyWiki web browser session.
So please make the viewing of internal PDF's working. I saw that you already places a pdf.dll in the root of the TiddlyDesktop directoryTree. But it seems so, that this isn't used.
With process monitor a find out that TiddlyDesktop find the application for opening the internal pdf by searching the registry for the open method for  the content type application/pdf. This leads to AcroRd32 in my case. But as I already stated currently only "Couldn't load plugin" is displayed by  TiddlyDesktop.

**Comment by Jermolene** [comment]
Hi @mmohr007 there's a new release of TiddlyDesktop that includes an update to the latest NW.js, which in turn now includes a PDF viewer. Please give it a try:

https://github.com/Jermolene/TiddlyDesktop/releases/tag/v0.0.9
