### ISSUE TITLE
Unable to activate wiki window

### ISSUE THREAD

**Issue by begin-again** [Jermolene/TiddlyDesktop#93]
I am having a continuing problem when opening a tiddlywink file. I can see that the window for the file is open by hovering over the windows 7 taskbar, but am unable to activate the window. Removing the wiki from the list of files in the "TiddlyDesktop - Main" window and re-adding does not work.  If I open a backup everything works just fine. Oddly though, if I rename the backup file to match the original name, the same old problem results.

**Comment by begin-again** [comment]
So far this is only affecting one of my wikis, the largest. Also, if I re-name the original wiki file then it will open just fine.

**Comment by Jermolene** [comment]
Hi @begin-again is this is the same problem discussed in #83?

**Comment by begin-again** [comment]
Yes it is - sorry to replicate. Was thrown of by "Main" in the issue title.

**Comment by begin-again** [comment]
Well now that I read some more of that issue 83, are they taking about the "TiddlyDesktop - Main" window or the actual window for an individual TiddlyWiki? My issue is with the TiddlyWiki.

**Comment by Jermolene** [comment]
Hi @begin-again the problem can occur with any window, and the resolution should be the same.

**Comment by begin-again** [comment]
OK, I found this in the layout file of the wiki

`
{
    "state": "minimized",
    "x": -32000,
    "y": -32000,
    "width": 1339,
    "height": 961
}
`

**Comment by begin-again** [comment]
Duplicate of #83
