### ISSUE TITLE
Internal JavaScript Error after opening external links

### ISSUE THREAD

**Issue by jekuno** [Jermolene/TiddlyDesktop#94]
Clicking any URL on a Wiki page opens this URL in a separate window.

Closing this window shows:

```
Internal JavaScript Error
Well, this is embarrassing. It is recommended that you restart TiddlyWiki by refreshing your browser.
Uncaught ReferenceError: gui is not defined
```

**Comment by Jermolene** [comment]
Hi @jekuno can you confirm which version of TiddlyDesktop you're using? Clicking on a URL within TiddlyDesktop should open the link in your default browser, as set in your operating system. Which operating system and browser are you using?

**Comment by jekuno** [comment]
MacOSX, Firefox, TiddlyDesktop 0.0.7 (7)

The URLs opened correctly in the default browser before updating TiddlyWiki to the most recent version.

**Comment by jekuno** [comment]
Ok, with 0.0.8 it's working again. I think some formulars got mixed up in my homebrew. Thanks!

**Comment by Jermolene** [comment]
Great, glad you hear things are ok @jekuno
