### ISSUE TITLE
 empty plugin library

### ISSUE THREAD

**Issue by axgo** [Jermolene/TiddlyDesktop#97]
I've worked with the file some and later decided I wanted to include a Plugin, when I ago look for it, it comes back with the Plugin Library/repository to be empty, Plugins(0) and Themes(0), is there a way to recuperate it and not have to Import all the Tiddlers form file A to File B?

**Comment by tobibeer** [comment]
1. Can you describe the exact steps you did, one by one?
2. Please give more details about your general setup (OS, etc...)

**Comment by Jermolene** [comment]
Hi @axgo there's a new release of TiddlyDesktop that should fix this problem:

https://github.com/Jermolene/TiddlyDesktop/releases/tag/v0.0.9

Please let me know how you get on.
