### ISSUE TITLE
Bad x and y coordinates stored if windows are minimised

### ISSUE THREAD

**Issue by steronydh** [Jermolene/TiddlyDesktop#98]
I've found that the x and y coordinates of Wiki windows are erroneously saved as -32000 if the window is minimised when the Main window is closed. It doesn't happen if the Wiki windows are open when the Main window is closed.

(Similar to [#83](https://github.com/Jermolene/TiddlyDesktop/issues/83))

**Comment by MichaelSD** [comment]
I can confirm this bug. You can get the window back by maximising it. (Win64)

**Comment by RyanBabij** [comment]
The current workaround:
shift-right click on application in taskbar. Select maximise. If you want it non-maximised, drag the title bar to reset the x,y coordinates and resize it.

**Comment by Jermolene** [comment]
Hi @steronydh @RyanBabij apologies for the delayed response. There is now an update to TiddlyDesktop that should fix this issue:

https://github.com/Jermolene/TiddlyDesktop/releases/tag/v0.0.9

Let me know how you get on.

**Comment by steronydh** [comment]
Thanks, @Jermolene, the update fixes this problem.
