### ISSUE TITLE
[Query] Can you access node.js-based TW from TW-Desktop?

### ISSUE THREAD

**Issue by kwill** [Jermolene/TiddlyDesktop#99]
My understanding is that
* running a standalone TiddlyWiki requires a single HTML file and a browser, and stores tiddlers in the HTML file
* running the [node.js version of TiddlyWiki](https://github.com/Jermolene/TiddlyWiki5) means running your own "server" process, accessed through a browser, and stores tiddlers as individual files
* TiddlyDesktop is a customised browser that makes it easier to use TiddlyWikis

Can you use TiddlyDesktop to access a node.js-based TiddlyWiki? In other words, getting the benefits of a customised browser and the benefits of running a server process (if that's what you prefer).

Or, is TiddlyDesktop only used to access standalone TiddlyWikis?

**Comment by dixonge** [comment]
Damn. I can't believe this is still open and unanswered!

**Comment by Jermolene** [comment]
Hi @kwill apologies for the delayed response...

You can indeed use TiddlyDesktop to access a Node.js based TiddlyWiki. Use the "Browse for wiki folder" button on the main screen. However, support for wiki folders has some significant limitations and should be considered experimental:

<<<
* Wiki folder windows cannot be re-opened once closed, other than by closing and restarting the application
* Wiki folder windows cannot be removed from the wiki list once they have been opened, other than by closing and restarting the application
* TiddlyDesktop cannot extract the favicon or title
* The only way to see errors on the server is to use the JavaScript console in TiddlyDesktop's developer tools.
<<<

**Comment by yatesco** [comment]
Thanks @Jermolene - does nodejs need to be `listen`ing for that wiki or does TiddlyDesktop automatically start nodejs or does it do something different?

I much prefer nodejs' tiddler-per-file layout but I really like TiddlyDesktop's list of wikis so want to use both :-).

**Comment by itsamenathan** [comment]
@yatesco if you use `tiddlywiki mynewwiki --init server` to create the wiki.  TiddlyDesktop can be used to "open" the `mynewwiki` directory.  I believe this is what you are looking for.
